### ISSUE TITLE
option to invert Output

### ISSUE THREAD

**Issue by tiwo85** [tobiasfaust/ESP8266_PumpControl#10]
When direct IO is configured as output, the switching is inverted. It would be nice if there is an option to invert the output.

**Comment by tobiasfaust** [comment]
please upload a screenshot of "ventil config" page.
When you press "Set on" the IO pin will switch to off (0V) ?

**Comment by tiwo85** [comment]
The pin must switch to GND to switch on the relais

**Comment by tobiasfaust** [comment]
Hi,
ich versteh das Problem noch nicht. Ich habe am ESP sowohl ein Einzelrelais der das Bypass 3wegeVentil ansteuert an den GPIOs dran, als auch ein 8-kanal Relaisboard per PCF und alle beiden funktionieren. 
Welche Hardware mienst du und wie äußert sich das aktuelle Schaltverhalten?

**Comment by tiwo85** [comment]
Ich habe diese Relais :
https://www.amazon.de/AZDelivery-2-Relais-Optokoppler-Low-Level-Trigger-Arduino/dp/B078Q326KT
Der verbaute Optokoppler schaltet das Relais, wenn der Eingangspin auf GND
gezogen wird. Wenn ich die Relais an einen PCF anschließe, dann
funktioniert auch alles mit der korrekten Logik, weil der PCF bei mir immer
nach GND schaltet. Hier mal ein Beispiel :
https://www.kinder-technik.de/1test-tabelle/portexpander2_schaltplan/
Ich konnte mir aber nun mit einem simplen Transistor Inverter helfen
https://cdn.sparkfun.com/assets/learn_tutorials/1/9/3/logic-inverter-circuit.png

tobiasfaust <notifications@github.com> schrieb am Fr., 5. Juni 2020, 11:38:
