### ISSUE TITLE
OLED Display doesn't work

### ISSUE THREAD

**Issue by tiwo85** [tobiasfaust/ESP8266_PumpControl#11]
**Describe the bug**
OLED-Display doesn't work. Address ist 3C/0x78 . Examples from library are working well, but with this firmware not.

**Comment by tobiasfaust** [comment]
please upload screenshots of "status" page and "basic config" page.

**Comment by tiwo85** [comment]
<a href="https://www.directupload.net/file/d/5819/5otjiqu7_png.htm" target="_blank"><img src="https://s12.directupload.net/images/200514/temp/5otjiqu7.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>
<a href="https://www.directupload.net/file/d/5819/eptsqnfs_png.htm" target="_blank"><img src="https://s12.directupload.net/images/200514/temp/eptsqnfs.png" border="1" title="Kostenlos Bilder und Fotos hochladen"></a>

**Comment by tobiasfaust** [comment]
please switch Pin SDA and Pin SCL and OLED works
