### ISSUE TITLE
elektronischer Kugelhahn als Alternative zu bistabilen Magnetventilen ?

### ISSUE THREAD

**Issue by rcmcronny** [tobiasfaust/ESP8266_PumpControl#24]
@tobiasfaust 
Hallo,

ich wollte die Wasserversorgung im Aussenbereich,welche aus einer Zisterne versorgt wird mit einem Magnetventil ausstatten, aktuell habe ich nur ein Kugelhahn zum Abstellen, was etwas unkonfortabel ist. (Primär wenn Frost ist, damit die Teil der Aussenleitung nicht einfriert)
Ich habe mir also ein 5V bistabiles Magentventil gekauft und eingebaut, allerdings habe ich die Mindestdruckangabe wohl nicht gesehen, das reicht einfach nicht. Da ich aber kein Magnetventil nutzen möchte, das den Winter über dauerhaft aktiv ist,damit die Leitung zu ist bzw andersrum, im Sommer dauerhaft aktiv ist, damit Wasser fliesst, kam ich auf die Idee, doch so ein Elektrischen Kugelhahn zu nutzen. 
Die werden auch angesteuert wie bistabile Magnetventile, allerdings brauchen die halt länger, bis sie auf/zu sind (ich las von 5-15s, muss man wohl je nach Druck usw ausmessen).

Bei den Einstellungen kann man jedoch nur max 999ms angeben, so das das nicht klappen würde.

Siehst Du da Möglichkeiten, das mit einzubauen ?
Alternativ wäre auch ein Magnetventil bistabil (also Impulsgesteuert) ohne Mindestdruck möglich, ich finde nur keine)

Der hier zB schwebt mir vor:
https://www.amazon.de/BACOENG-Motorkugelhahn-Zonenventil-Elektrische-Kugelventil/dp/B00YMH02FA/

**Comment by tobiasfaust** [comment]
Hi,
soweit ich das sehen konnte benötigen die Magnetventile immer einen Mindestdruck.
Anders die 2-/3 Wegeventile, allerdings benötigen diese, wie du schon geschrieben hast permanenten Strom für eine Stellung, auch wenn diese im mA Bereich liegt.

Das ich die Zeit auf 999ms begrenzt habe liegt daran, das eine Erhöhung sich sehr negativ auf MQTT und den Webserver niederschlägt. MQTT würde abbrechen und der Webservice laggt. 

Ich habe auch so einen Kugelhahn bzw ein 3WegeVentil welches 15-20sek benötigt. Allerdings habe ich in einem Zustand auch immer Strom anliegend
gruss
