### ISSUE TITLE
Links to binarys in releases.json not working

### ISSUE THREAD

**Issue by hackepeterOli** [tobiasfaust/ESP8266_PumpControl#26]
Some binary links in releases.json not working (Error 403)

- http://tfa-releases.s3-website.eu-central-1.amazonaws.com/ESP8266_PumpControl/ESP8266_PumpControl.ino.v2.4.4-53.PROD.bin
- http://tfa-releases.s3-website.eu-central-1.amazonaws.com/ESP8266_PumpControl/ESP8266_PumpControl.ino.v2.4.5-59.PRE.bin
- ...

**Comment by tobiasfaust** [comment]
sorry, a bug of changing the naming conventions by adding ESP32 support.
I hope now all files are correct..
