### ISSUE TITLE
Ventil-Config verloren mit 4 Bistabilen relays

### ISSUE THREAD

**Issue by dkotte** [tobiasfaust/ESP8266_PumpControl#30]
Ver 2.5.3 - 90 (PRE)
Wemos D1 mini + 2 Motor-Shield V1  
mit 1-2 konfigurierten Ventilen an Port 130+131 funktioniert alles problemlos.
Nach Reboot oder Power-lost ist die Konfiguration noch i.O.
mit 4 konfigurierten Ventilen geht die Konfiguration der Ventile bei Reboot oder Power-Fehler verloren.

**Comment by tobiasfaust** [comment]
Probier mal bitte einen ESP32 zu nehmen. 
Ich muss mir die Speichernutzung nochmal ansehen. Wenn die Config verloren geht ist i.d.R. die Speichernutzung zu hoch.
Alternativ müsste ich Funktionalität aus dem ESP8266 entfernen bzw nur im ESP32 erlauben :( (zb. 1Wire)

**Comment by popeye1979** [comment]
Hatte heute das gleiche Problem mit einem D1 mini mit 4 normalen Ventilen in der Config. Nach Reboot waren wieder die 2 Default-Einträge vorhanden und die 4 Ventile weg.
Habe dann auf ESP32 getestet und das Problem tritt dort nicht auf.

**Comment by tobiasfaust** [comment]
Ich werde die Funktionalitäten für den ESP8266 einschränken um Speicherplatz frei zu bekommen. 
Wer diese dann braucht muss auf ESP32 umsteigen.
