### ISSUE TITLE
WT32-ETH01 Support

### ISSUE THREAD

**Issue by hackepeterOli** [tobiasfaust/ESP8266_PumpControl#31]
Ist es möglich pumpcontrol auf dem WT32-ETH01 zum laufen zu bringen?

**Comment by tobiasfaust** [comment]
möglich schon, aber ETH wird nicht laufen. Ich habe bisher nicht nicht die korrekten Parameter gefunden um ein ETH am ESP32 zum Laufen zu bewegen. 
Eine Testversion habe ich schon fertig, nur funktioniert sie noch nicht :(

**Comment by hackepeterOli** [comment]
Schade, implementiert hast du es jetzt nicht?

**Comment by tobiasfaust** [comment]
Doch, ist implementiert bei mir lokal aber die Initialisierung des ETH funktioniert nicht.  Da scheinen die Parameter noch nicht korrekt zu sein. Selbst mit einem offiziellen TEstsketch läuft es nicht. Ich hatte mit einem Olimex getestet. 
Falls du ein TestSketch mit dem ETH zum laufen bekommst übernehme ich die Einstellungen gerne

**Comment by hackepeterOli** [comment]
Ja, gerne. Welchen Sketch hattest du getestet?

**Comment by tobiasfaust** [comment]
ich habe diese hier genommen. Ich hatte kein Waveshare LAN8720, aber eben ein olimex Board welches LAN schon drauf hatte.
Sketche: https://github.com/espressif/arduino-esp32/tree/master/libraries/Ethernet/examples
LAN8720: https://www.waveshare.com/lan8720-eth-board.htm
Olimex ESP32 EVB: https://www.olimex.com/Products/IoT/ESP32/ESP32-EVB/open-source-hardware
