### ISSUE TITLE
MQTT User and Password

### ISSUE THREAD

**Issue by Maddin2020** [tobiasfaust/ESP8266_PumpControl#7]
I want use your great Code with my Smart Home Openhab App. Now my MQTT Broker have a Password and a Username. Is it possible to created fields for User and password. Thanks a lot !

**Comment by tobiasfaust** [comment]
solved by last commit https://github.com/tobiasfaust/ESP8266_PumpControl/commit/1ea962e5f08faef268681487ff33537a0e8bfb36

Please check if its works due my local mqtt server dont need authentification
